### ISSUE TITLE
Investigate possible buffering of BAM access

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/CaVEMan#20]
M/Estep do all reads from disk in ~60KB chunks.  This is explainable as this is the size of the compressed blocks (65536 b) of a BAM file.

Is it possible to stage the data in a buffered stream, I know 1MB would work better for lustre, not sure about EC2?

**Comment by drjsanger** [comment]
BAM access is done by samtools. Buffer size changes have been suggested on several occasions
