### ISSUE TITLE
generateCavemanUMNormVCF - command line help has errors

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/CaVEMan#28]
@drjsanger , looks like some of this is a bit squiffy.  In usage program name doesn't match and some of the param short names don't appear in the description area.

    $ generateCavemanUMNormVCF -h
    Usage: generateCavemanVCFUnmatchedNormalPanel -i jobindex [-f path] [-c int] [-m int] [-e int] 

    -i  --index [int]                 Job index (e.g. from $LSB_JOBINDEX)

    -b  --bam-files [file]            Path to the bam files to be analysed (comma separated list, in the same order as sample-names).
    -o  --out-file [file]             Filename to write results to.
    -r  --reference [file]            Path to reference file (genome.fa).
    -l  --split-sections [file]       Path to the bed file of split sections to analyse.
    -s  --species [string]            Species name (used in VCF output).
    -v  --spp-vers [string]           Species version (used in VCF output).
    -n  --sample-names [string]       Name of samples being analysed (comma separated list, in the same order as bam-files).
    -p  --platform [string]           Platform sample was generated on (Illumina). [default:Illumina]
    -t  --protocol [string]           Protocol used to generate sample data (WGS|WXS). [default:WGS]
    Optional
    -q  --min-base-qual [int]         Minimum base quality [default:0]
    -h	help                          Display this usage information.

**Comment by drjsanger** [comment]
Fixed in 1.7.3
