### ISSUE TITLE
Crash when encountering a "bad" read

### ISSUE THREAD

**Issue by DaGaMs** [cancerit/CaVEMan#36]
I've been trying to test CaVEMan on some exome sequencing data that I downloaded from the EGA. The data seems to have been pre-processed with GATK (indel realignment/base quality recalibration). When I run CaVEMan (tag 1.6.2), I get the following crash during `mstep`:

    ~/Code/CaVEMan/build/bin/caveman mstep -i 1 -f D132.cfg
    Looking at section chr1:1-9188602 for mstep
    M-stepping section chr1:1-564449 for mstep
    fetched a reference seq of length 564449 for this section.
    M-stepping section chr1:570372-724136 for mstep
    fetched a reference seq of length 153765 for this section.
    M-stepping section chr1:727044-825006 for mstep
    fetched a reference seq of length 97963 for this section.
    M-stepping section chr1:825116-2583334 for mstep
    fetched a reference seq of length 1758219 for this section.
    [ERROR] (src/algos.c: algos_mstep_read_position:180 errno: No such file or directory) Error calculating map qual index.
    *** glibc detected *** /users/bschuster/Code/CaVEMan/build/bin/caveman: double free or corruption (fasttop): 0x0000000002621550 ***
    Segmentation fault

I've concluded that this is actually due to a sanity check on some reads in `algos_mstep_read_position(` but I wonder 

 - what is causing this assertion to fail and 
 - why the app then goes into meltdown

I can't share the full data unfortunately but I'd be happy to test and report back.

**Comment by drjsanger** [comment]
Hi @DaGaMs ,

Are you able to run this code with valgrind (valgrind <caveman command>). It'll give me a better idea of which lines it's failing at. 

Thanks

**Comment by drjsanger** [comment]
Hi @DaGaMs 

Are you able to give me a range of mapping qualities that your data uses please?

Dave

**Comment by DaGaMs** [comment]
[Here's a gist](https://gist.github.com/DaGaMs/c2cc5273c15d7b642deb) with the first 1000 reads from one of the files.

**Comment by drjsanger** [comment]
@DaGaMs 

This error will be occurring if you have a read with a mapQ > 60 and mapQ != 255. These are the ranges used as covariate ranges for CaVEMan. Since the SAM spec says 0-255 are valid I think perhaps I should add another mapQ range of 61-254 to ensure all valid mapQs are covered, however we've never encountered mapQs > 60 and < 255 hence this not being spotted before.
Looking at your read examples I can't see a mapping quality that is not in the ranges 0-60 or 255, perhaps you could check if that's what's causing this error in your data please?

Dave

**Comment by DaGaMs** [comment]
Hi Dave, I had a scan through the file with `samtools view Tumour/_EGAZ00001081833_bmmrd_D132.realigned-recalibrated.bam | perl -ne '@l=split; print if $l[4]<0 or $l[4]>255 or $l[4]>60 and $l[4]!=255'` and found a ton of reads that have mapq values that violate your definition above. Here's the first 10:

https://gist.github.com/DaGaMs/13b3826a946a7f227000#file-mapq_gt60-sam

**Comment by DaGaMs** [comment]
I think I found the source of this problem. In the [GATK forums](http://gatkforums.broadinstitute.org/discussion/2724/why-does-indelrealigner-change-mapq-from-70-to-80), it says:

>When reads are realigned, the confidence with which they are mapped increases. Specifically, the tool adds 10 to the MQ of reads that get realigned. The underlying assumption is that their original MQs were made artificially lower because of the mismatching "SNPs" (which are actually artifacts).

**Comment by drjsanger** [comment]
That would explain why we've never seen the quality scores go over 60 unless they're 255. I'll roll out a bugfix version soon.

**Comment by DaGaMs** [comment]
Thanks! What trips me up about this is that the supplementary material for the paper which accompanied this dataset states that 

> The paired-end FASTQ files were aligned to the genome (to UCSC’s hg19 GRCh37) with BWA24 (v0.5.9). Duplicate paired-end sequences were removed using Picard MarkDuplicates (v1.35) to reduce potential PCR bias. Aligned reads were realigned for known insertion/deletion events using SRMA (v0.1.155). Base quality scores were recalibrated using the Genome Analysis Toolkit (v1.1-28). Somatic substitutions were identified using MuTect (v1.1.4) or CaVEMaN.

The data they sent just doesn't match that description. I couldn't get neither MuTect nor CaVEMaN to actually process the files, and the indel realignment was clearly done using GATK tools and not SRMA, as it says in the bam headers. I guess I shouldn't be surprised but it's another example of the state of Bioinformatics Methods reporting...

**Comment by drjsanger** [comment]
Oh dear... 
Well, 1.6.3 contains the fix. Hopefully you'll have more luck running it now. Let me know if you find any more issues. Dave
