### ISSUE TITLE
Error with caveman setup command

### ISSUE THREAD

**Issue by rdbcasillas** [cancerit/CaVEMan#42]
During the installation process all tests seem to have passed without applying any manual patch to htslib. But when I use caveman setup or setupCaveman, I get the following error:

```
caveman: src/alg_bean.c:279: alg_bean_write_list_char: Assertion `((li)->count) > 0' failed.
./setupCaveman: line 35: 30077 Aborted                 (core dumped) ${0%/*}/caveman setup "$@"

```

I am hoping this is being caused because of not applying the patch to htslib. If yes, shouldn't the tests reflect that instead of passing successfully?

**Comment by drjsanger** [comment]
Morning,

Admittedly this isn't a clear error message so some data state needs catching. 
Just to check the obvious first: do your bam headers have '@RG' lines, and if so do they each have a unique ID field?
The htslib patch applied in the setup script was a fix to index reading (and is now in the newer releases of htslib) so shouldn't affect this step.

**Comment by rdbcasillas** [comment]
Thanks drjsanger,
I had to create bam files with RG using picard. First step has been cleared! Can you tell me what " -i" option for the split means? It wasn't clear from the docs. My reference fasta index file looks like this:

```
1       249250621       52      60      61
2       243199373       253404903       60      61
3       198022430       500657651       60      61
4       191154276       701980507       60      61
5       180915260       896320740       60      61
6       171115067       1080251307      60      61
7       159138663       1254218344      60      61
8       146364022       1416009371      60      61
9       141213431       1564812846      60      61
10      135534747       1708379889      60      61
11      135006516       1846173603      60      61
12      133851895       1983430282      60      61
13      115169878       2119513096      60      61
14      107349540       2236602526      60      61
15      102531392       2345741279      60      61
16      90354753        2449981581      60      61
17      81195210        2541842300      60      61
18      78077248        2624390817      60      61
19      59128983        2703769406      60      61
20      63025520        2763883926      60      61
21      48129895        2827959925      60      61
22      51304566        2876892038      60      61
X       155270560       2929051733      60      61
Y       59373566        3086910193      60      61
MT      16569   3147273397      70      71
```

Thanks again for quick response!

**Comment by drjsanger** [comment]
In the split step -i is the index used to look up which contig a job works on in the reference.fai file. So for your reference you'll require a job for each value of i from 1..25. 
In the m and e steps -i refers to a line in the splitList the split step generates.
