### ISSUE TITLE
any best practices for RNA-seq SNV calling?

### ISSUE THREAD

**Issue by davidroberson** [cancerit/CaVEMan#53]
Wanting to run some T/N pairs through but retaining normal variants.  Normal tissue has been irradiated.  Are ASCAT CN values optional?

Thanks

Dave

**Comment by drjsanger** [comment]
Hi Dave, ASCAT CN values are optional. CaVEMan does require a contamination value and can have CN defaults set. 

If you provide 0.1 as normal contamination, 5 as tumour CN and 2 and normal CN you will be giving CaVEMan a broader range over which it will call variants (Unless you have more accurate estimates CN and contamination). Bear in mind this will cause genotype alleles called to be output as NN/TTTTT .
