### ISSUE TITLE
caveman mstep with error: split_access_get_section_from_indexv Error opening split list file.

### ISSUE THREAD

**Issue by dongqing7** [cancerit/CaVEMan#59]
Hello,
I'm using 1.11.0, and followed the “Processing flow” in the main page. When running the command after:

```
bin/caveman setup -t testData/testing_mt.bam -n testData/testing_wt.bam -r testData/ref.fai -g testData/ign.test -f results/
bin/caveman split -i 1 -f caveman.cfg.ini
```

The command:
`bin/caveman mstep -f caveman.cfg.ini -i 1`
throw the error meg:

> [ERROR] (src/split_access.c: split_access_get_section_from_index:50 errno: No such file or directory) Error opening split list file.
[ERROR] (src/mstep.c: mstep_main:193 errno: None) Error fetching region from split file.
Segmentation fault (core dumped)

It seemed that the code in split_access.c didn't combined the info -i. Is there something wrong with my parameters?

**Comment by drjsanger** [comment]
@dongqing7 
Do you have the `splitList.`1 file present? 
Do you have a  file named `splitList` present (created by merging the outputs from the split step)?

**Comment by dongqing7** [comment]
Thank you for reply. No, I found that splitList.1 file should be created manually. Now the tool work nice! Thank you for great work!
