### ISSUE TITLE
CAVEMAN: Somatic Calls in SNPs File

### ISSUE THREAD

**Issue by vyellapa** [cancerit/CaVEMan#60]
We have been using Caveman to call variants in our high depth(200X) WGS bams. We are seeing that some true calls are currently being put into the snps file. 

Below is an example where a true call with 16% VAF in Tumor and 0% VAF in Normal is not in the somatic file but the snps file. 

I wanted to ask if there is a way we can rescue such calls in a systematic way. 
Thank you,
Teja

yellapav$ zless ALL101-T2-1-D1-1_vs_ALL101-N1-1-D1-1.snps.ids.vcf.gz|grep 25380285
12 25380285 70a63090-7430-11e6-a392-90a00151774b
G A . . DP=325;MP=4.8e-05;GP=1.0e+00;TG=GG/AG;TP=4.8e-05;SG=AG/GG;SP=1.0e+00
GT:FAZ:FCZ:FGZ:FTZ:RAZ:RCZ:RGZ:RTZ:PM 0|0:0:0:20:0:0:0:17:0:0.0e+00 0|1:19:1:112:1:26:0:129:0:1.6e-01

**Comment by drjsanger** [comment]
1. There is a minor bug in the sorting of genotypes called as AG/GG in CaVEMan but was displayed as a somatic genotype - Where the top genotype has a variant allele, but this allele isn't seen in the relevant sample (normal in this case doesn't contain any 'A's) the second genotype is selected. I will open this as a separate issue. 

2. The call itself looks somatic (and clearly is from the data), however:
I think what has happened here is that a CN of 2 in the tumour with 0.15 contamination would mean that the expected VAF for a (clonal) somatic mutation could only be 0.85 or 0.425. The observed value is 0.16 with very high coverage, which is clearly a long way away from the expectation. Therefore, CaVEMan thinks that the most likely solution is an AG SNP with just the wild-type G allele present in the tumour cells. That is, It thinks all the observed A reads come from the contaminating normal cells and it is presuming that by chance the A allele was not observed in the much lower coverage normal sample. Formally, mathematically, this is correct given the choices we gave CaVEMan – that is, there is no bug in the computation – it is truly more likely that the observed data come from a SNP than from a clonal somatic mutation in CN 2 with 0.15 normal contamination.
 
In reality, of course, this is a somatic mutation, not a germline SNP – but it’s either a subclonal somatic mutation or the copy number in the tumour isn’t 2 or the normal contamination isn’t 0.15. However we didn't give those values to CaVEMan.
 
This call is heavily driven by the high coverage of the tumour sample – 281 reads. This penalises heavily when the observed VAF is a long way away from its expectation. The policy we’ve adopted when running high coverage data through CaVEMan (eg targeted gene screens and exomes) is to increase the copy number of the tumour sample – this gives it more options for expected VAF, and then it almost always finds the variant as a somatic mutation (as it does here when you set the CN as 3). 

As a default for samples with no copynumber information we use a normal contamination of 10% and a tumour CN of 5, this provides the sensitivity we require.

**Comment by vyellapa** [comment]
Thank you Dave.
