### ISSUE TITLE
estep help for options -l and -r

### ISSUE THREAD

**Issue by sfbrunner** [cancerit/CaVEMan#61]
Hi folks, just a small issue. I noticed that the help entries for the estep -l and -r options say:
`Normal protocol. Ideally this should match -r/-l but not checked (WGS|WGX|RNA) [default:WGS].`

However, when trying to use "WGX" you get an error:
`Normal protocol 'WGX' is invalid should be one of (WGS|WXS|RNA).`

Best, 
Simon

**Comment by drjsanger** [comment]
Thanks for pointing this out Simon. Looks like a bug in the documentation. If you use WXS for now this should work. However I believe WGX and WXS are used by different groups to represent exome data. I will investigate and either make both valid or correct the help docs.
