### ISSUE TITLE
Error opening file to read cov array

### ISSUE THREAD

**Issue by suimye** [cancerit/CaVEMan#62]
Hi,
I got the error at the merge process described below.    

> caveman setup -t $tumourBam -n $normalBam -r $REF -g $IGN    

for the test run, I use -i 1   

> caveman split -i 1 -f $INI
> mv splitList.1 splitList
>caveman mstep -f $INI -i 1

```
Created results directory './results'.
Found chr: 1 of length: 249250621 at index 1
Found 0 ignored regions for chromosome 1.
Looking at section 1:1-928895 for mstep
M-stepping section 1:1-464448 for mstep
fetched a reference seq of length 464448 for this section.
M-stepping section 1:464449-928895 for mstep
fetched a reference seq of length 464447 for this section.
Created directory ./results/1.
```

###  I got the error from the merge process for covs files

> caveman merge -f $INI

```
[ERROR] (src/covs_access.c: covs_access_read_covs_from_file:167 errno: No such file or directory) Error opening file to read cov array: ./results/1/928896_1222529.covs.
```    

When I check the folder, the file "928896_1222529.covs" could not find out in the "results" folder. And also only the file "1_928895.covs" was generated.

```
-bash-4.1$ ls results/1/
1_928895.covs

```

I also check the splitList. The splitList have 502 lines in the file.   

```
1	0	928895
1	928895	1222529
1	1222529	1527127
1	1527127	1893065
1	1893065	2189793
1	2189793	2464429
1	2464429	2763184
```
It seemed that the mstep didn't generate the other covs files. Do you have any idea for solve this error?

Suimye

**Comment by drjsanger** [comment]
Have you run the other mstep jobs? You would need to have run 

```
caveman mstep -i 1
caveman mstep -i 2
caveman mstep -i ... 
caveman mstep -i 502
```

in order to generate all files expected by the merge step. These could be run as a job array.

**Comment by suimye** [comment]
Oh.. I misunderstood "-i" means.   
In the mstep, "-i" must input all of the number of the mstep jobs.   
OK, I success to generate covs_arr and probs_arr files with no error!!   

Great thanks!
