### ISSUE TITLE
split.c - cli options parsed but never used

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/CaVEMan#65]
Primarily, should they just be ignored and `--read-count` be used on it's own?

Two of the variables indicated as used in refinement of split size don't appear to be used:

Search for [increment](https://github.com/cancerit/CaVEMan/search?utf8=%E2%9C%93&q=increment) (`increment`)
* Declared as default
* Updated via optarg if present
* Variable never used

Search for [maxPropRdCount](https://github.com/cancerit/CaVEMan/search?utf8=%E2%9C%93&q=maxPropRdCount) (`--max-read-count`)
* Declared as default
* Updated via optarg if present
* Variable never used

**Comment by drjsanger** [comment]
I think we need to remove them. Since we moved the split step to run through the file a read at a time rather than retrieve sections the increment and max PropRdCount are defunct.

**Comment by keiranmraine** [comment]
Okay, we can schedule those for a clean up, I can do the wrapper work with them in place.
