### ISSUE TITLE
error in caveman estep 1.12.0

### ISSUE THREAD

**Issue by Sdgr90** [cancerit/CaVEMan#70]
[ERROR] (src/output.c: output_vcf_header:302 errno: No such file or directory) Error (0) writing contigs.
[ERROR] (src/estep.c: estep_main:517 errno: None) Error writing header to muts file.

**Comment by drjsanger** [comment]
@Sdgr90 Are you able to provide the CaVEMan command you are running please? This error would occur if the output file was not found or unavailable for writing.

**Comment by Sdgr90** [comment]
I have 5 regions of chr21 and i'm trying follow command line 
for i in {1..5}; do caveman estep -i $i; done

**Comment by Sdgr90** [comment]
I have 5 regions of chr21 and i'm trying follow command line
for i in {1..5}; do caveman estep -i $i; done

**Comment by drjsanger** [comment]
You may like to try using the [CaVEMan wrapper code] https://github.com/cancerit/cgpCaVEManWrapper). Which was made to simplify the process of running CaVEMan.

The things I'd check first are:

1. Do you have permissions to write to the directory you're outputting to? 
2. Do you have space left on the drive you are writing to?
3. Do the contents of the generated caveman.cfg file seem sensible (it will be named `caveman.cfg.ini`)? 

Without any more detail it is hard to diagnose what the issue is.

**Comment by drjsanger** [comment]
Further investigation leads me to believe this is zlib related. Can you confirm which version of zlib is installed on your system please?

**Comment by Sdgr90** [comment]
Hi, David
My zlib version is 1.2.8.

**Comment by drjsanger** [comment]
Just to make sure that caveman is using the expected zlib and not linkng to a different version, could you check the following are the same `libz.so` file please? 

-  `ldd <path to your caveman executable> | grep libz` 
-  `ldconfig -v | grep libz.so`

I can reproduce this error using libz-1.2.3.4, but using libz-1.2.8 works. I just want to ensure it's the same problem causing the error. If not I'll have to try and dig deeper.

**Comment by drjsanger** [comment]
I'm sure it's how you found out already, but if you could also run `ldconfig -v | grep libz.so` on the machine you're running caveman on it will give the libz version on the system.

**Comment by Sdgr90** [comment]
Hi
In macOS what are the corresponding commands ldd or  ldconfig ? 
I’m not able to find its … 
Thank you

**Comment by drjsanger** [comment]
Ah ok, CaVEMan isn't tested on MacOS X, and I doubt a mac will have enough compute power to run CaVEMAn in a timely manner. Are you running caveman on the mac itself or a remote computer/farm?

**Comment by Sdgr90** [comment]
I was trying to use Caveman on OS X only for testing purposes, but I could run Caveman on CGC cloud, so if I remember well it’s linux environment.
