### ISSUE TITLE
Pre-release tag overlapping_reads

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/CaVEMan#76]
Pull all hotfixes into this feature and create a pre-release tag for use in large scale testing via docker.

Note: for some reason this branch isn't `feature/overlapping_reads`.  Needs renaming,

**Comment by drjsanger** [comment]
Branch renamed to a [feature/overlapping_reads](https://github.com/cancerit/CaVEMan/tree/feature/overlapping_reads)

**Comment by drjsanger** [comment]
Prerelease tag made and linked in cgpCaVEManWrapper.

**Comment by drjsanger** [comment]
Released in [1.13.0](https://github.com/cancerit/CaVEMan/tree/1.13.0)
