### ISSUE TITLE
what do these mean please

### ISSUE THREAD

**Issue by beginner984** [cancerit/CaVEMan#89]
Sorry,

I have been given Caveman results for copy number in cancer Vs normal patients. I have 154 individual .csv with these headers

Chromosome	Start	End	Total_CN	Minor_CN
1	14930	817901	3	0
1	825877	2515957	4	2
1	2522392	5719471	2	1
1	5726928	5736123	2	0
1	5736184	7750025	3	1
1	7750243	12302420	4	2
1	12341092	14152449	3	1
1	14154723	14243772	1	0
1	14259402	16820646	3	1
1	16822459	16833852	6	3
1	16834064	17191019	4	1
1	17191103	17227649	4	0
1	17227972	17235144	6	2
1	17235176	17275018	3	0
1	17285573	17631023	3	1

Could you please help me getting how I know which genes has copied segment? Because in my understanding this file only says on each chromosome in this position we have such number of copied segments. 

Thanks for any help

**Comment by drjsanger** [comment]
Hi @beginner984 

This looks like an older style output from [ASCAT](https://github.com/cancerit/ascatNgs) [wiki](https://github.com/cancerit/ascatNgs/wiki). With further information in the [Current Protocols in Bioinformatics paper](https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpbi.17). It likely has 'cave' in the name as it can be processed to be used by CaVEMan as copy number input. 

If these pages don't resolve your questions please do contact us on the ASCAT issues page.

Dave
